apiVersion: apps/v1
kind: Deployment
metadata:
  name: octetosample
  labels:
    app: octetosample
spec:
  replicas: 1
  selector:
    matchLabels:
      app : octetosample
  template:
    metadata:
      labels:
        app: octetosample
    spec:
      containers:
      - name: octetosample
        image: dhronan/octetosample
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name:  octetosample-svc
spec:
  selector:
    app:  octetosample
  ports:
  - port:  80
    targetPort:  8080
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octetosample-lb
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: octetosample-svc
                port: 
                    number: 8080